namespace HackETS2TrucksBook
{
    using System;
    using System.ComponentModel;
    using System.Runtime.ExceptionServices;
    using System.Runtime.InteropServices;
    using System.Windows.Forms;

    public class MyForm : Form
    {
        private PictureBox pictureBox1;
        private Label label2;
        private Label label4;
        private Label label5;
        private Timer timer1;
        private CheckBox checkBox2;
        private CheckBox checkBox3;
        private CheckBox checkBox4;
        private CheckBox checkBox6;
        private CheckBox checkBox7;
        private CheckBox checkBox8;
        private CheckBox checkBox9;
        private CheckBox checkBox11;
        private CheckBox checkBox12;
        private Label label1;
        private Label label3;
        private CheckBox checkBox13;
        private CheckBox checkBox14;
        private CheckBox checkBox15;
        private Label label6;
        private Button button1;
        private CheckBox checkBox16;
        private CheckBox checkBox17;
        private CheckBox checkBox18;
        private CheckBox checkBox10;
        private Timer timer2;
        private Label label8;
        private Label label7;
        private CheckBox checkBox19;
        private CheckBox checkBox21;
        private Timer timer3;
        private Button button2;
        private Label label9;
        private Label label10;
        private Label label11;
        private Label label12;
        private Label label13;
        private Timer timer4;
        private Timer timer5;
        private Timer timer6;
        private Timer timer7;
        private Label label15;
        private CheckBox checkBox24;
        private TextBox textBox1;
        private TextBox textBox2;
        private Timer timer8;
        private Timer timer9;
        private CheckBox checkBox25;
        private CheckBox checkBox26;
        private Label label14;
        private CheckBox checkBox1;
        private CheckBox checkBox5;
        private CheckBox checkBox20;
        private CheckBox checkBox22;
        private IContainer components;

        public MyForm();
        private void ~MyForm();
        private void Bitdefender();
        private void Bitdefender2();
        private void Bitdefender3();
        private void Bitdefender4();
        private void button1_Click(object sender, EventArgs e);
        private void button2_Click(object sender, EventArgs e);
        private void button3_Click(object sender, EventArgs e);
        private void CbOooN();
        private void CbOooNOF();
        private void checaratualização();
        private void checkBox1_CheckedChanged(object sender, EventArgs e);
        private void checkBox10_CheckedChanged(object sender, EventArgs e);
        private void checkBox11_CheckedChanged(object sender, EventArgs e);
        private void checkBox12_CheckedChanged(object sender, EventArgs e);
        private void checkBox13_CheckedChanged(object sender, EventArgs e);
        private void checkBox14_CheckedChanged(object sender, EventArgs e);
        private void checkBox15_CheckedChanged(object sender, EventArgs e);
        private void checkBox16_CheckedChanged(object sender, EventArgs e);
        private void checkBox17_CheckedChanged(object sender, EventArgs e);
        private void checkBox18_CheckedChanged(object sender, EventArgs e);
        private void checkBox19_CheckedChanged(object sender, EventArgs e);
        private void checkBox2_CheckedChanged(object sender, EventArgs e);
        private void checkBox20_CheckedChanged(object sender, EventArgs e);
        private void checkBox21_CheckedChanged(object sender, EventArgs e);
        private void checkBox22_CheckedChanged(object sender, EventArgs e);
        private void checkBox24_CheckedChanged(object sender, EventArgs e);
        private void checkBox3_CheckedChanged(object sender, EventArgs e);
        private void checkBox4_CheckedChanged(object sender, EventArgs e);
        private void checkBox5_CheckedChanged(object sender, EventArgs e);
        private void checkBox6_CheckedChanged(object sender, EventArgs e);
        private void checkBox7_CheckedChanged(object sender, EventArgs e);
        private void checkBox8_CheckedChanged(object sender, EventArgs e);
        private void checkBox9_CheckedChanged(object sender, EventArgs e);
        private void crasharj();
        private void difffffffffff();
        [HandleProcessCorruptedStateExceptions]
        protected override void Dispose([MarshalAs(UnmanagedType.U1)] bool A_0);
        private void fllll();
        private void fllllff();
        private void InitializeComponent();
        private void label1_Click(object sender, EventArgs e);
        private void lkkkkkk();
        private void lkkkkkkun();
        private void mensagem();
        private void mrrrrrr();
        private void MyForm_Load(object sender, EventArgs e);
        private void nD();
        private void nDdddCg1();
        private void nDdddCg2();
        private void nDdddOff();
        private void nnnnnc();
        private void nnnnncf();
        private void pnc1();
        private void pnc2();
        private void pnc3();
        private void pncdes();
        private void prot();
        private void prot1();
        private void prot10();
        private void prot11();
        private void prot12();
        private void prot2();
        private void prot3();
        private void prot4();
        private void prot5();
        private void prot6();
        private void prot7();
        private void prot8();
        private void prot9();
        private void sppergAd();
        private void sppergOf();
        private void sppergSb();
        private void sppppAd();
        private void sppppdf();
        private void sppppdf2();
        private void sppppSb();
        private void tilp();
        private void tilpcem();
        private void tilpnovnov();
        private void tilpumoitzero();
        private void tilpumsetmeia();
        private void tilpumsetoito();
        private void timer1_Tick(object sender, EventArgs e);
        private void timer2_Tick(object sender, EventArgs e);
        private void timer3_Tick(object sender, EventArgs e);
        private void timer4_Tick(object sender, EventArgs e);
        private void timer5_Tick(object sender, EventArgs e);
        private void timer6_Tick(object sender, EventArgs e);
        private void timer7_Tick(object sender, EventArgs e);
        private void timer8_Tick(object sender, EventArgs e);
        private void timer9_Tick(object sender, EventArgs e);
        private void v1();
        private void vcemcem();
        private void vnovnov();
        private void voff();
        private void vrum1();
        private void vrum2();
        private void vumsetmeia();
        private void vumsetoito();
        private void wap1();
        private void wap2();
        private void wap25();
        private void wap3();
    }
}

